### ISSUE TITLE
Does not work with Spring meta annotations

### ISSUE THREAD

**Issue by eperret** [salesforce/AptSpring#31]
When applying `@Verified` to a bean annotated with a meta annotated `@component` it causes multiple compile errors.  See https://github.com/forcedotcom/aura/blob/d77bb57ea56ddf769d2be961c3c97afecffc42ce/aura-spring/src/main/java/org/auraframework/annotations/Annotations.java#L42

**Comment by eperret** [comment]
@rexhoffman can you close this bug?

**Comment by rexhoffman** [comment]
basic support is added, but there are cases where nested meta-annotations will break.
